### ISSUE TITLE
[bug] 多轮会话导致tokens超载

### ISSUE THREAD

**Issue by ac1982** [Ulov888/chatpdflike#2]
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4658 tokens (3158 in your prompt; 1500 for the completion). Please reduce your prompt; or completion length.

**Comment by Ulov888** [comment]
The reason for this error is that gpt3-turbo limits the input length to 4096 tokens, you can modify the length of max_tokens in the response function., but it maybelimit the length of your generated text.
